### ISSUE TITLE
Document nightly toolchain requirement

### ISSUE THREAD

**Issue by stefnotch** [ripytide/nodit#58]
I think it'd be worthwhile to document that this crate requires a nightly Rust toolchain for the time being
https://github.com/ripytide/nodit/blob/fac00b8c4f3aef27526fe09290a141ff7a556960/src/lib.rs#L377-L379

**Comment by ripytide** [comment]
I just checked and we're not actually using `btree_cursors` or `step_trait` anymore, it's unfortunate there doesn't seem to be a lint for unused features. Regarding `let_chains` I use them twice so it may be better so simply refactor those to use normal match statements and allow this library to be used on stable.

**Comment by stefnotch** [comment]
Oh sweet, I had no idea it'd be this easy to get this library to run on stable Rust.

Would you like to do the refactors, or should I?

**Comment by ripytide** [comment]
I'll do them/already done them just testing them on stable now.

**Comment by ripytide** [comment]
released as `v0.7.1`

**Comment by stefnotch** [comment]
Thank you very much!
